### ISSUE TITLE
How do I get otp_secret and otp_credential_id?

### ISSUE THREAD

**Issue by thais-molica** [babangsund/cypress-keycloak#25]
Hi, I'm trying to authenticate to my API which uses OTP to login, but I'm having a hard time figuring out where do i find the otp_secret and the otp_credential_id.

I'm not sure this would be the place to ask, it's more of a keycloak question, but since there is an example in the documentation I was hoping someone could give any kind of directions.

Thanks

**Comment by ddavid09** [comment]
Hi, I see that issue is quite old, but I allow myself to answer, how I handled that. 
To extract `otp_credential_id` I used keycloak REST API. 
`GET: http://{host-name}/admin/realms/{realm}/users/{userId}/credentials` before that you have to get access token for admin for authorization (additional keycloak configuration can be required).

To extract `otp_secret` I used WinAuth software as OTP authenticator - it allows to export secret

**Comment by nedredmond** [comment]
Another solution for OTP secret, for new accounts:

In my cypress test, I am generating new users and going through the setup flow. If you have OTP turned on, you will be prompted to set up MFA on first login. Clicking the link under the QR code exposes the secret, a base-32 string 32 characters long.

```
    cy.get("#mode-manual").should("exist").click(); // click "I can't scan"
    cy.get("#kc-totp-secret-key").should("exist").invoke("text"); // grab otp secret
```

From there, you can assign this to an alias, write it to a file, or do whatever else you would like to preserve it. Note that you will need to strip out the whitespace to use it. To remove any characters that are not base 32, I did: `const formattedSecret = rawSecret.replace(/[^A-Z2-7]/gi, "");`

**Comment by babangsund** [comment]
Thanks for the answers. I think this is solved.
